language: node_js

node_js:
  - 'stable'

install: npm install

services:
  - postgresql

script: npm test

before_script:
  - psql -c 'create database test_automart;' -U postgres
  - npm install nyc@13.2.0 coveralls cross-env -g

after_script: cross-env NODE_ENV=test npm run coveralls